sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t ashishlakra13/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ashishlakra13/docker-react npm run test